/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybankmachine;

import java.util.Scanner;

/**
 *
 * @author lukas
 */
public class ATMgui extends javax.swing.JFrame {
    String bankName1;
    double balance1 = 0;
    double toBalance1;


    /**
     * Creates new form ATMgui
     */
    public ATMgui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bankNameLabel = new javax.swing.JLabel();
        enterBalanceLabel = new javax.swing.JLabel();
        bankNameInput = new javax.swing.JTextField();
        $amountInput = new javax.swing.JTextField();
        depositButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        mainOutput = new javax.swing.JLabel();
        interestDaysLabel = new javax.swing.JLabel();
        interestDaysInput = new javax.swing.JTextField();
        interestButton = new javax.swing.JButton();
        mayNotNeedOutput = new javax.swing.JLabel();
        errorOutput = new javax.swing.JLabel();
        inOutMoneyInput = new javax.swing.JLabel();
        interestRateInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(670, 388));

        bankNameLabel.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        bankNameLabel.setText("Enter bank name:");

        enterBalanceLabel.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        enterBalanceLabel.setText("Enter interest rate (%):");

        depositButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        withdrawButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        mainOutput.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        mainOutput.setText("I am here");

        interestDaysLabel.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        interestDaysLabel.setText("Enter amount of days to accrue interest: ");

        interestButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        interestButton.setText("Calculate Interest");
        interestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestButtonActionPerformed(evt);
            }
        });

        mayNotNeedOutput.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        mayNotNeedOutput.setText("I am also here");

        errorOutput.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        errorOutput.setText("ERROR");

        inOutMoneyInput.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        inOutMoneyInput.setText("Enter amount($) to withdraw or deposit:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bankNameLabel)
                                        .addComponent(bankNameInput)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(4, 4, 4)
                                            .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent($amountInput))
                                    .addComponent(inOutMoneyInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mayNotNeedOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(interestDaysLabel)
                                .addComponent(interestDaysInput)
                                .addComponent(enterBalanceLabel)
                                .addComponent(interestRateInput, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(interestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interestDaysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interestDaysInput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inOutMoneyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent($amountInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interestRateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(interestButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(depositButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mayNotNeedOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(errorOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
      
        if (bankNameInput.getText().isEmpty() || $amountInput.getText().isEmpty()) {
            //Nothing
        }
        
        else {                                             
            bankName1 = bankNameInput.getText();        
            toBalance1 = Double.parseDouble($amountInput.getText());
            
            System.out.println("Your balance is: " + (balance1+=toBalance1));
            //ATM THINGYDINGY = new ATM (bankName1, balance1, toBalance1, true);
        }
        
        //ATM THINGYDINGY = new ATM(bankName1, toBalance1);
        //System.out.println("Your balance is now " + (toBalance1));
        
        /*String bankName = bankNameInput.getText();
        double toBalance = Double.parseDouble($amountInput.getText());
        System.out.println("Your balance is now " + (toBalance));*/
    }//GEN-LAST:event_depositButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        /*
        
        bankName1 = bankNameInput.getText();
        toBalance1 = Double.parseDouble($amountInput.getText());
        //toBalance1 = toBalance1 * -1;
        System.out.println("Your balance is now " + (toBalance1));
        /*String bankName = bankNameInput.getText();
        double toBalance = Double.parseDouble($amountInput.getText());
        System.out.println("Your balance is now " + (0 - toBalance));*/
        
        
        if (bankNameInput.getText().isEmpty() || $amountInput.getText().isEmpty()) {
            //Nothing
        }
        
        else {                                             
            bankName1 = bankNameInput.getText();        
            toBalance1 = Double.parseDouble($amountInput.getText());
            
            System.out.println("Your balance is: " + (balance1-=toBalance1));
            //ATM THINGYDINGY = new ATM(bankName1, balance1, toBalance1, false);
        }
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void interestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATMgui().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField $amountInput;
    private javax.swing.JTextField bankNameInput;
    private javax.swing.JLabel bankNameLabel;
    private javax.swing.JButton depositButton;
    private javax.swing.JLabel enterBalanceLabel;
    private javax.swing.JLabel errorOutput;
    private javax.swing.JLabel inOutMoneyInput;
    private javax.swing.JButton interestButton;
    private javax.swing.JTextField interestDaysInput;
    private javax.swing.JLabel interestDaysLabel;
    private javax.swing.JTextField interestRateInput;
    private javax.swing.JLabel mainOutput;
    private javax.swing.JLabel mayNotNeedOutput;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}